Repository ucsb-cs156-f24/proj-happycows-f24-12, pull requests merged in 2024-11, with the labels that each got.

#22 Minor UX Fix - made explanation of buying and selling cows neater
  frontend/src/main/components/Commons/ManageCows.js
Labels: 5

#20 Sort by leaderbord wealth bug fix
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: 10

#21 Fixed visual ugliness on profits table
  frontend/src/main/components/Commons/PagedProfitsTable.js
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
Labels: 5, Merge Candidate-CI

#23 Yungong - UX fix, changing buy/sell into title case
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/components/Commons/ManageCowsModal.js
  frontend/src/tests/components/Commons/ManageCows.test.js
  frontend/src/tests/components/Commons/ManageCowsModal.test.js
Labels: 5, Merge Candidate-CI

#27 Issue 16 - Change link of Mattanjah de Vries in footer
  frontend/src/main/components/Nav/Footer.js
Labels: 5, Merge Candidate-CI

#41 Adding DB table for Course
  src/main/java/edu/ucsb/cs156/happiercows/entities/Course.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CourseRepository.java
  src/main/resources/db/migration/changes/Courses.json
Labels: 5, Merge Candidate-CI

#43 Create DB Table for Students
  src/main/java/edu/ucsb/cs156/happiercows/entities/Student.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/StudentRepository.java
  src/main/resources/db/migration/changes/CreateCourseStudentTable.json
Labels: 5, Merge Candidate-CI

#38 yx - Fixed Create Announcement
  frontend/src/main/components/Announcement/AnnouncementForm.js
  frontend/src/main/pages/AdminAnnouncementsPage.js
  frontend/src/main/pages/AdminCreateAnnouncementsPage.js
  frontend/src/tests/components/Announcement/AnnouncementsForm.test.js
  frontend/src/tests/pages/AdminAnnouncementsPage.test.js
  frontend/src/tests/pages/AdminCreateAnnouncementsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 10, Merge Candidate-CI

#51 yungong - try to add tests for ManageCows
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/tests/components/Commons/ManageCows.test.js
Labels: 10, Merge Candidate-CI

#49 Yungong - displaying announcement table on play page updated
  frontend/src/fixtures/pagedAnnouncementFixtures.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/components/Commons/PagedAnnouncementTable.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/components/Commons/PagedAnnouncementTable.test.js
  frontend/src/tests/pages/AdminCreateAnnouncementsPage.test.js
  frontend/src/tests/pages/AdminViewPlayPage.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 10, Merge Candidate-CI

#71 Mr-OurTable testing - Reduced runtime and maintained testing accuracy
  frontend/src/tests/components/OurTable.test.js
Labels: 20, Merge Candidate-CI

#57 yungong - try to add CommonsPlay exception test
  frontend/src/main/components/Commons/CommonsPlay.js
  frontend/src/tests/components/Commons/CommonsPlay.test.js
Labels: 10, Merge Candidate-CI

#61 Fixed Incorrect Capitalization
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/components/Commons/ManageCows.js
Labels: 5, Merge Candidate-CI

#65 Dynamic Previous and Next Buttons for Profits Column
  frontend/src/main/components/Commons/PagedProfitsTable.js
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
Labels: 10, Merge Candidate-CI

#67 Create CourseController, add GET (index) and POST (create)
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CourseController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Course.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CourseControllerTests.java
Labels: 10, Merge Candidate-CI

#69 COURSE DB: add DELETE
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CourseController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CourseControllerTests.java
Labels: 10, Merge Candidate-CI

#47 Abby-Add in Get_ALL function to Student and add function to upload roster on student
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/StudentRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
Labels: 10, FIXME-update-deployment, LAST CALL: Update Deployment
